spring.application.name=Snap Cart
spring.autoconfigure.exclude=org.springframework.ai.vectorstore.mongodb.autoconfigure.MongoDBAtlasVectorStoreAutoConfiguration


#MongoDb connection
spring.data.mongodb.uri=mongodb://localhost:27017/SnapCart


# Google Gemini API Configuration  
gemini.api.key=AIzaSyCz5dN_JLdQzDcvapbj86uMOiCCNyTxR0w
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent

# Google Cloud Vertex AI Configuration (for Gemini Pro Vision)
# You need to set up a Google Cloud Project and enable Vertex AI API
gemini.project.id=your-google-cloud-project-id
gemini.location=us-central1



