spring.application.name=Snap Cart
spring.autoconfigure.exclude=org.springframework.ai.vectorstore.mongodb.autoconfigure.MongoDBAtlasVectorStoreAutoConfiguration


#MongoDb connection
spring.data.mongodb.uri=mongodb://localhost:27017/SnapCart


# Google Gemini API Configuration  
gemini.api.key=AIzaSyCz5dN_JLdQzDcvapbj86uMOiCCNyTxR0w
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent



